CREATE VIEW candidate_targeting_summary AS
SELECT
    COALESCE(target_segment, 'Not targeted') AS target_segment,
    COUNT(*) AS candidates
FROM candidate_targeting_2026
GROUP BY COALESCE(target_segment, 'Not targeted');

CREATE VIEW yearly_finance_kpis AS
WITH income_by_year AS (
    SELECT CAST(strftime('%Y', transaction_date) AS INTEGER) AS calendar_year,
           SUM(amount) AS income
    FROM stg_income
    GROUP BY CAST(strftime('%Y', transaction_date) AS INTEGER)
),
expense_by_year AS (
    SELECT CAST(strftime('%Y', transaction_date) AS INTEGER) AS calendar_year,
           SUM(amount) AS expense
    FROM stg_expenses
    GROUP BY CAST(strftime('%Y', transaction_date) AS INTEGER)
),
trainees_by_year AS (
    SELECT cohort_year AS calendar_year, COUNT(DISTINCT candidate_id) AS trainees
    FROM stg_candidates
    GROUP BY cohort_year
),
years AS (
    SELECT calendar_year FROM income_by_year
    UNION SELECT calendar_year FROM expense_by_year
    UNION SELECT calendar_year FROM trainees_by_year
)
SELECT
    y.calendar_year,
    ROUND(COALESCE(i.income, 0), 2) AS income,
    ROUND(COALESCE(e.expense, 0), 2) AS expense,
    ROUND(COALESCE(i.income, 0) - COALESCE(e.expense, 0), 2) AS net_result,
    COALESCE(t.trainees, 0) AS trainees,
    ROUND(COALESCE(e.expense, 0) / NULLIF(t.trainees, 0), 2) AS cost_per_trainee
FROM years AS y
LEFT JOIN income_by_year AS i USING (calendar_year)
LEFT JOIN expense_by_year AS e USING (calendar_year)
LEFT JOIN trainees_by_year AS t USING (calendar_year);

CREATE VIEW expense_category_rank AS
WITH category_totals AS (
    SELECT expense_category, SUM(amount) AS total_expense
    FROM stg_expenses
    GROUP BY expense_category
)
SELECT
    expense_category,
    ROUND(total_expense, 2) AS total_expense,
    ROUND(100.0 * total_expense / NULLIF(SUM(total_expense) OVER (), 0), 2) AS expense_share_pct,
    DENSE_RANK() OVER (ORDER BY total_expense DESC) AS expense_rank
FROM category_totals;

CREATE VIEW debt_kpis AS
SELECT
    ROUND(SUM(total_debt), 2) AS total_debt,
    ROUND(SUM(paid_amount), 2) AS paid_amount,
    ROUND(SUM(remaining_debt), 2) AS remaining_debt,
    COUNT(DISTINCT candidate_id) AS candidates,
    SUM(CASE WHEN certificate_issue_date IS NULL THEN 1 ELSE 0 END) AS certificates_not_issued
FROM stg_exam_accounts;

-- These three inputs are documented summary figures, not rows generated by the public demo.
CREATE VIEW reported_funnel_reconciliation AS
WITH documented_counts AS (
    SELECT 200 AS targeted_contacts, 47 AS interested, 12 AS enrolled
)
SELECT
    targeted_contacts,
    interested,
    enrolled,
    ROUND(100.0 * interested / NULLIF(targeted_contacts, 0), 2) AS contact_to_interest_pct,
    ROUND(100.0 * enrolled / NULLIF(interested, 0), 2) AS interest_to_enrolment_pct,
    ROUND(100.0 * enrolled / NULLIF(targeted_contacts, 0), 2) AS contact_to_enrolment_pct,
    'Reported snapshot; period and row-level source are not public' AS evidence_scope
FROM documented_counts;

CREATE VIEW pipeline_reconciliation AS
SELECT
    (SELECT COUNT(*) FROM raw_candidates) AS candidates,
    (SELECT COUNT(*) FROM raw_exam_accounts) AS exam_accounts,
    (SELECT COUNT(*) FROM raw_income) AS tuition_receipts,
    (SELECT COUNT(*) FROM raw_expenses) AS expense_rows,
    (SELECT COUNT(*) FROM raw_other_income) AS other_income_rows,
    (SELECT COUNT(*) FROM candidate_targeting_2026 WHERE target_segment IS NOT NULL) AS target_candidates;

